### ISSUE TITLE
Why doens't works on 1.16?

### ISSUE THREAD

**Issue by Mataisplays** [aematsubara/Roulette#10]
Hi! my server its in paper 1.16.5, but when i tried to use the plugin, an internal error ocurred, and in the spigot page says that all versions are compatible 1.12 - 1.19 except 1.16, why?

**Comment by aematsubara** [comment]
Hi! you can find the reason here: https://www.spigotmc.org/resources/roulette.82197/field?field=documentation under the section "Why is 1.16 not supported?"

Unfortunately, there's no fix for that and I can't get the player input if they dismount, even hypixel had to block 1.16 for a specific minigame because of that https://hypixel.net/threads/update-blocking-1-16-in-turbo-kart-racers.3128241/#post-21760636

**Comment by Mataisplays** [comment]
Thank u ^_^
